<?php

/**
 * Implements hook_ctools_plugin_api().
 */
function adapt_core_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_field_wrapper_elements_alter().
 */
function adapt_core_field_wrapper_elements_alter(&$wrapper_elements) {
  // Add more wrapper options
  $wrapper_elements['ul'] = t('UL');
  $wrapper_elements['ol'] = t('OL');
  $wrapper_elements['li'] = t('LI');
  $wrapper_elements['dl'] = t('DL');
  $wrapper_elements['dt'] = t('DT');
  $wrapper_elements['dd'] = t('DD');
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Hide adapt_core specific features from the features interface
 * can be enabled by settings adapt_modify_core to TRUE.
 */
function adapt_core_form_features_admin_form_alter(&$form, &$form_state) {
  if (variable_get('adapt_modify_core', FALSE) == FALSE) {
    $form['adapt']['#access'] = FALSE;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Add a few improvements to the features interface
 */
function adapt_core_form_features_export_form_alter(&$form, &$form_state) {
  // Do not export menu links in features
  if (isset($form['export']['menu_links'])) {
    $form['export']['menu_links']['#access'] = FALSE;
  }

  // We want the Generate feature button to be easily accessible.
  $form['advanced']['#collapsed'] = FALSE;

  // Lets do a few tweaks if we are within a non standard install profile.
  $profile = variable_get('install_profile', 'standard');
  if (!in_array($profile, array('standard', 'minimal'))) {
    // Lets supply some good defaults for the developer.
    if ($form['info']['package']['#default_value'] == 'Features') {
      $form['info']['package']['#default_value'] = $profile;
    }

    if (empty($form['advanced']['generate_path']['#default_value'])) {
      $form['advanced']['generate_path']['#default_value'] = "profiles/{$profile}/modules/custom";
    }
  }
}
