<?php

/**
 * @file
 * Adapt reusable ctools plugins
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
function adapt_chaos_plugins_ctools_plugin_directory($owner, $plugin_type) {
  // We'll be nice and limit scandir() calls.
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return "plugins/$plugin_type";
  }
}

/**
 * Implements hook_theme().
 */
function adapt_chaos_plugins_theme() {
  $tpl_path = drupal_get_path('module', 'adapt_chaos_plugins') . '/tpl';

  return array(
    'cookie_information' => array(
      'template' => 'cookie-information',
      'variables' => array('message' => ''),
      'path' => $tpl_path,
    ),
  );
}
