<?php

/**
 * @file:
 * Settings and variables for Adapt Core module
 */

// List of modules to enable on install. All these must be present in the .make
// file of adapt_core
$modules_enable = array(
  'adapt_features',
  'adminimal_admin_menu',
  'devel',
  'entity_token',
  'entity_view_mode',
  'field_ui',
  'googleanalytics',
  'jquery_update',
  'linkit',
  'menu_block',
  'menu_trail_by_path',
  'page_manager',
  'pm_existing_pages',
  'rules',
  'views_content',
  'views_ui',
  'xmlsitemap',
  'xmlsitemap_node'
);
