<?php

/**
 * @file:
 * Settings and variables for Adapt Core module
 */

// List of modules to enable on install. All these must be present in the .make
// file of adapt_core
/*
$modules_enable = array(
  'adminimal_admin_menu',
  'entity_dependency',
  'entity_token',
  'entity_view_mode',
  'field_group',
  'field_wrappers',
  'fieldable_panels_panes',
  'googleanalytics',
  'jquery_update',
  'linkit',
  'menu_block',
  'menu_trail_by_path',
  'page_manager',
  'pm_existing_pages',
  'rules',
  'smart_trim',
  'uuid',
  'views_content',
  'xmlsitemap',
  'xmlsitemap_node',
  'rdf',
  'update',
);
*/
